
const movies=[
     {title:'How to train your Dragon',description:'A hapless young Viking who aspires to hunt dragons becomes the unlikely friend of a young dragon himself, and learns there may be more to the creatures than he assumed.',rate:3,url:"dragon.jpg"},
     {title:'Extraction',description:'Tyler Rake, a fearless black market mercenary, embarks on the most deadly extraction of his career when he is enlisted to rescue the kidnapped son of an imprisoned international crime lord.',rate:2,url:"extraction.jpg"},
     {title:'The hunger game',description:'The Hunger Games is an annual event in which one boy and one girl aged 12–18 from each of the twelve districts surrounding the Capitol are selected by lottery to compete in a televised battle royale to the death. The book received critical acclaim from major reviewers and authors.',rate:5,url:"hunger-game.jpg"},
     {title:'The incredible',description:'Mr Incredible is possibly his world is most powerful hero. He possesses vast superhuman strength and durability. He also is highly agile and is a skilled combatant, though perhaps his greatest power is the willingness to keep going in the face of seemingly unbeatable odds.',rate:5,url:"incredibles.jpg"},
     {title:'Jumanji',description:'"JUMANJI" is a 1995 American fantasy adventure film about Judy Shepherd (Kirsten Dunst) and Peter Shepherd (Bradley Pierce), who move into a longtime empty house and discover a supernatural board game that makes wild animals and other jungle hazards materialize upon each players move.',rate:4,url:"jumanji.jpg"},
     {title:'Mulan',description:'Mulan is a girl, the only child of her honored family. When the Huns invade China, one man from every family is called to arms. Mulan is father, who has an old wound and cannot walk properly, decides to fight for his country and the honor of his family though it is clear that he will not survive an enemy encounter.',rate:4,url:"mulan.jpg"},
     {title:'The narnia King',description:'A King is the male ruler of an independent state or country.During times of war, Kings would usually take an active role in leading their army in battle. Kings have the authority to dismiss and appoint people in charge of Narnian islands. They also have the power to enact the death penalty against their enemies as appropriate.',rate:1, url:"narnia.jpg"},
     {title:'Old guard',description:'A covert team of immortal mercenaries is suddenly exposed and must now fight to keep their identity a secret just as an unexpected new member is discovered.',rate:3, url:"oldguard.png"},
     {title:'OnWard',description:'Set in a suburban fantasy world, the film follows two elf brothers who set out on a quest to find an artifact that will temporarily bring back their deceased father. Onward premiered at the 70th Berlin International Film Festival on February 21, 2020 and was theatrically released on March 6, 2020',rate:5, url:"onward.jpg"},
     {title:'Power',description:'"Power" is a visionary drama that straddles the glamorous Manhattan lifestyles of the rich and infamous and the underworld of the international drug trade. The cast is led by Omari Hardwick as James "Ghost" St.',rate:5,url:"power.jpg"},
     {title:'Close',description:'Close is a 2019 action thriller film directed by Vicky Jewson and starring Noomi Rapace.[2][3] Rapace is character is based on that of Jacquie Davis, one of the world is leading female bodyguards, whose clients have included J. K. Rowling, Nicole Kidman and members of the British royal family',rate:4,url:"close.jpg"},
     {title:'Spider Man',description:'Spider-Man is a fictional superhero created by writer-editor Stan Lee and writer-artist Steve Ditko. He first appeared in the anthology comic book Amazing Fantasy',rate:4,url:"spider.png"},
    ];

export default movies 